### ISSUE TITLE
(DE) Versionsnummer wurde nach security patch nicht geändert.

### ISSUE THREAD

**Issue by d4s6** [devmount-mozilo/FileInfo#11]
Nach Übernahme des security patchs #10 in den `master`-Branch wurde die Versionsnummer nicht angepasst. Dies erschwert die Kommunikation bzgl. der Updatenotwenigkeit.

**Comment by devmount** [comment]
Version mit ead8236b9be84e6f0733b59d2ced66615fb36cc3 aktualisiert.

**Comment by drdf** [comment]
Danke.
